### ISSUE TITLE
Can I revise this code to add more functionality?

### ISSUE THREAD

**Issue by Jacktherookie** [Armitxes/VSCode_SQF#40]
Hello, I'm currently using this extension for VSCode. Since I know there is a sensitive copyright issues, I can modify anything from your file. so I'm asking you is there any way to modify the code and add more features from following link
https://sqf.bisimulations.com/

**Comment by dosfx** [comment]
+1

In the meantime any advice for quickly adding commands that I know for sure are valid commands so it looks better while this is worked on?

**Comment by Jacktherookie** [comment]
> +1

This site contains all of commands and functions but I'm not sure info about functions can be extracted from site. I guess I'll make my own syntax correction and highlighting addons.

**Comment by dosfx** [comment]
https://sqf.bisimulations.com/display/SQF/Text+Editors

Has language definitions for a couple of other editors. Gonna try my hand at converting one of them to the vscode json format.

**Comment by Armitxes** [comment]
Sorry, was on vacation for 3 weeks. You are more than welcome to revise modify any of the files.

You can simply do so by [forking](https://help.github.com/en/articles/fork-a-repo) this repository which creates a copy for yourself. Make all the changes you wish in there, others may as well join you.

If you wish to share and are happy with yours changes, GitHub offers to automatically merge your fork into this repository and will automatically add you and whoever else may helped you as contributor to this repository. Proper credits will be given in the release notes as well.

Otherwise you may do your very own thing in the fork.

For your changes to work, they must be done in your vs code extension directory - by default located at: `%USERPROFILE%\.vscode\extensions`

If you need any help please feel free to ask at any time ;)
